source_directories:
    - /mnt/source
    - /mnt/vaultwarden/attachments

repositories:
    - path: /mnt/borg-repository

one_file_system: true
archive_name_format: 'backup-{now}'

keep_hourly: 2
keep_daily: 7
keep_weekly: 4
keep_monthly: 12
keep_yearly: 10

checks:
    - name: repository
    - name: archives

check_last: 3

commands:
    - before: action
      when:
        - create
      run:
        - echo "Starting a backup job..."

    - after: action
      when:
        - create
      run:
        - echo "Backup created..."

    - after: action
      when:
        - create
        - prune
        - compact
        - check
      run:
        - echo "Uploading backup..."
        - rclone sync /mnt/borg-repository nextcloud:nextcloud-backup -P --dry-run
        - rclone sync /mnt/borg-repository nextcloud:nextcloud-backup -v
        - 'curl -H "Authorization: Bearer ${NTFY_TOKEN}" -d "Creation and uploading of backup successful" -H "Title: Backup done" ${NTFY_URL}/${NTFY_TOPIC}'

    - after: error
      run:
        - echo "Error while creating a backup."
        - 'curl -H "Authorization: Bearer ${NTFY_TOKEN}" -d "Creation of backup failed. Check borgmatic logs." -H "Title: Error creating backup" ${NTFY_URL}/${NTFY_TOPIC}'

mariadb_databases:
    - name: all
      hostname: db
      port: 3306
      username: root

sqlite_databases:
    - name: vaultwarden
      path: /mnt/vaultwarden/db.sqlite3
