location:
    source_directories:
        - /mnt/source
    repositories:
        - /mnt/borg-repository
    one_file_system: true

storage:
    compression: lz4
    archive_name_format: 'backup-{now}'

retention:
    keep_hourly: 2
    keep_daily: 7
    keep_weekly: 4
    keep_monthly: 12
    keep_yearly: 10
    prefix: 'backup-'

consistency:
    checks:
        - repository
        - archives
    check_last: 3
    prefix: 'backup-'

hooks:
    before_backup:
        - echo "Starting a backup job."
    after_backup:
        - echo "Backup created."
        - simplepush.sh -t "Backup created" -m "Creation of backup successful"
    on_error:
        - echo "Error while creating a backup."
        - simplepush.sh -t "Error creating backup" -m "Creation of backup failed. Check borgmatic logs."
    mysql_databases:
        - name: all
          hostname: db
          port: 3306
          username: root
          #options: "--single-transaction"

